---
title: An R Markdown document converted from "/content/go_analysis.ipynb"
output: html_document
---

### Import

```{r}
if (!requireNamespace("BiocManager")) install.packages("BiocManager")
BiocManager::install(c("clusterProfiler", "DOSE", "enrichplot", "org.Mm.eg.db"))
```

```{r}
install.packages(c("ggnewscale", "ggridges", "ggupset"))
```

```{r}
library(clusterProfiler)
library(DOSE)
library(enrichplot)
library(ggnewscale)
library(ggplot2)
library(ggupset)
library(org.Mm.eg.db)
```

## read data

```{r}
d <- read.csv("./output/forGO_up.csv", col.names = c("SYMBOL", "logFC"))
# d <- read.csv('./forGO_up.csv', col.names = c('SYMBOL', 'logFC')) assume that
# 1st column is ID 2nd column is fold change
head(d)
```

```{r}
ids <- data.frame(mapIds(org.Mm.eg.db, d$SYMBOL, "ENTREZID", "SYMBOL"))[, 1]
```

```{r}
## feature 1: numeric vector
geneList <- d[, 2]
## feature 2: named vector
names(geneList) <- as.character(ids)
## feature 3: decreasing order
geneList <- sort(geneList, decreasing = TRUE)
head(geneList)
length(geneList)
```

```{r}
de <- names(geneList)[abs(geneList) > 0]
length(de)
```

## enrichGo analysis

```{r}
ego_bp <- enrichGO(gene = de, OrgDb = "org.Mm.eg.db", keyType = "ENTREZID", ont = "BP",
    pvalueCutoff = 1, pAdjustMethod = "none", qvalueCutoff = 1, minGSSize = 10, maxGSSize = 500,
    readable = TRUE, pool = FALSE)
ego_mf <- enrichGO(gene = de, OrgDb = "org.Mm.eg.db", keyType = "ENTREZID", ont = "MF",
    pvalueCutoff = 1, pAdjustMethod = "none", qvalueCutoff = 1, minGSSize = 10, maxGSSize = 500,
    readable = TRUE, pool = FALSE)
ego_cc <- enrichGO(gene = de, OrgDb = "org.Mm.eg.db", keyType = "ENTREZID", ont = "CC",
    pvalueCutoff = 1, pAdjustMethod = "none", qvalueCutoff = 1, minGSSize = 10, maxGSSize = 500,
    readable = TRUE, pool = FALSE)
```

```{r}
summary(ego_mf)
```

```{r}
goplot(ego_mf, size=100)
```

```{r}
barplot(ego_cc, showCategory = 20, label_format = 18) + theme_classic()
```

```{r}
dotplot(ego_bp, showCategory = 20, label_format = 10) + theme_light()
```

```{r}
go <- enrichGO(de, OrgDb = "org.Mm.eg.db", ont = "all", pvalueCutoff = 1, pAdjustMethod = "none",
    qvalueCutoff = 1)
dotplot(go, split = "ONTOLOGY", showCategory = 6, label_format = 20) + facet_grid(ONTOLOGY ~
    ., scale = "free")
```

```{r}
## remove redundent GO terms ego2 <- simplify(ego_mf)
cnetplot(ego_mf, foldChange = geneList, node_label = "all", layout = "kk")
```

```{r}
cnetplot(ego_cc, foldChange = geneList, layout = "kk", circular = TRUE, colorEdge = TRUE)
```

```{r}
heatplot(ego_mf)
```

```{r}
heatplot(ego_cc, foldChange=geneList, label)
```

```{r}
upsetplot(ego_bp)
```

```{r}
edo2 <- enrichKEGG(names(geneList), organism = "mmu")
```

```{r}
summary(edo2)
```

```{r}
dotplot(ego3)
```

```{r}
ego3 <- gseGO(geneList     = geneList,
              OrgDb        = org.Mm.eg.db,
              ont          = "BP",         
              pvalueCutoff = 1,
              verbose      = FALSE)
```

```{r}
summary(ego3)
```

